services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - vslf-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:3000
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - vslf-network

networks:
  vslf-network:
    driver: bridge
